# Generated by Django 5.1.5 on 2025-05-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.CharField(max_length=255)),
                ("selected", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.avatar",
            ),
        ),
    ]
