# Generated by Django 5.1.5 on 2025-04-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar_opcion",
            new_name="avatar_option",
        ),
    ]
