# Generated by Django 5.1.5 on 2025-04-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_rename_avatar_opcion_user_avatar_option"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AvatarOpcion",
            new_name="AvatarOption",
        ),
    ]
