# Generated by Django 5.1.5 on 2025-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_avatar_remove_message_is_read_alter_user_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True,
                choices=[(1, "Héctor"), (2, "Manuel"), (3, "Ana"), (4, "Ingrid")],
                max_length=35,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Avatar",
        ),
    ]
