# Generated by Django 5.1.5 on 2025-04-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_rename_avataropcion_avataroption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_option",
        ),
        migrations.DeleteModel(
            name="AvatarOption",
        ),
    ]
