# Generated by Django 5.1.5 on 2025-05-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_user_avatar_delete_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interactions",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
