# Generated by Django 5.1.5 on 2025-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_user_interactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="rating_avatar",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Héctor"), (2, "Manuel"), (3, "Ana"), (4, "Ingrid")],
                null=True,
            ),
        ),
    ]
