# Generated by Django 5.1.5 on 2025-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_remove_user_avatar_option_delete_avataroption"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disponibility",
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
