# Generated by Django 5.1.5 on 2025-05-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_rating_rating_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="rating_avatar",
        ),
    ]
