# Generated by Django 5.1.5 on 2025-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_alter_message_options_message_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
