# Generated by Django 5.1.5 on 2025-05-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_location_user_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="disponibility",
        ),
    ]
